### ISSUE TITLE
check_connection() always throws exception when connected

### ISSUE THREAD

**Issue by Deccoyi** [FreeOpcUa/opcua-asyncio#1117]
I am trying to implement an isConnected function but I am not very familiar with python. These functions are inside a class.

Connect Function
```
    async def connect(self, url):

        print("Trying to connect")
        self.client = Client(url)
        await self.client.connect()
```
isConnected function
```
    async def isConnected(self):
            print("Check connection")
            await self.client.check_connection()

```

When I call isConnected() without calling Connect() it says self.client attribute does not exist. Which is expected and ok.
But when I call Connect() then isConnected() this happens. Bu I am sure I am connected because if I try to run client.get_node(...) it works.

```
Exception in thread Thread-2 (process_request_thread):
Traceback (most recent call last):
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncua\client\client.py", line 478, in _renew_channel_loop
    await asyncio.sleep(duration)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 363, in handle
    super().handle()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 427, in 
handle
    self.handle_one_request()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\http\server.py", line 415, in 
handle_one_request
    method()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 218, in __call__
    return call_result.result()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", 
line 439, in result
    return self.__get_result()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", 
line 391, in __get_result
    raise self._exception
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 284, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "C:\Users\COSKUN\Desktop\coskun\kalinlik-takip\api\main.py", line 53, in check_connection  
    print(await client.isConnected())
  File "C:\Users\COSKUN\Desktop\coskun\kalinlik-takip\api\opcuaReader.py", line 100, in isConnected
    await self.client.check_connection()
  File "C:\Users\COSKUN\AppData\Local\Programs\Python\Python310\lib\site-packages\asyncua\client\client.py", line 440, in check_connection
    await self._renew_channel_task
asyncio.exceptions.CancelledError

```

Is it a bug or  am I doing something wrong? As far as I understand check_connection() should only throw exception if connection is not possible or disconnected.

Is it ok to use client.connect() everytime I try to read value?

**Comment by oroulet** [comment]
there is something wrong in your setup. Are you using python 3.7?

**Comment by schroeder-** [comment]
You should connect once. Otherwise the function can't check if you are connected. Best is to use the with async with.

```Python
client = Client(...)
async with client:
    while 1:
       ....
```

**Comment by oroulet** [comment]
just added an example: https://github.com/FreeOpcUa/opcua-asyncio/blob/master/examples/client-reconnect.py

**Comment by Deccoyi** [comment]
> there is something wrong in your setup. Are you using python 3.7?

I am trying to use it with Flask and React. When a button clicked it will connect. Then I am planning to read values cyclicly with APScheduler.  I am using Python 3.10.2. I updated the library to 1.0.1. 

Thank yo I will look into your example

**Comment by Deccoyi** [comment]
hi I looked into your code but my case is a little different (I am a begginner). I am using flask routes to call the functions like this:
```
client = opcuaReader()
@app.route("/api/connect")
async def connect():
    global client
    global clientURL 
    clientURL = request.args["targetUrl"]
    if (await client.connect(clientURL)):
        return "Connected" , 200
    else:
        return "NotConnected", 200
```

connect function (inside a class) :

```
    async def connect(self, url):
        print("Trying to connect")
        self.client = Client(url)
        try:
            await self.client.connect()
        except Exception as e:
            print("Connection exception: " , e)
            return False
        else:
            print("Connected")
            return True
```

I have another route that calls get_node:

```
await self.client.connect() #if I don't add this here it doesn't work
self.unit = self.client.get_node("ns=2;s=unit/")
```

**Comment by Deccoyi** [comment]
> ```python
> self.client.check_connection()
> ```

unfortunately check_connection thrwos error. I guess I have to scrap that function. 

regarding your suggestion: this app will work with electron+react+python app. Electron browserwindow will be the only client.  and a PLC will be an opcua server.

Do you have a suggestion about my 2nd post? or should I create new post/issue about it?

**Comment by oroulet** [comment]
I am rather sure that if check_connection() fails then it is because you have a big issue in your code

**Comment by Deccoyi** [comment]
> I am rather sure that if check_connection() fails then it is because you have a big issue in your code

thats more likely  :)

**Comment by schroeder-** [comment]
You can activate the logging and look at the output maybe you get a clue where the opc ua clients connects/disconnects or has some other errors that require a reconnect.
