### ISSUE TITLE
`uadiscover` ImportError

### ISSUE THREAD

**Issue by driftregion** [FreeOpcUa/opcua-asyncio#167]
Running `uadiscover` fails with the following error

```
Endpoint 1:
Traceback (most recent call last):
  File "/home/njames/.local/bin/uadiscover", line 11, in <module>
    load_entry_point('asyncua==0.8.2', 'console_scripts', 'uadiscover')()
  File "/home/njames/repos/opcua-asyncio/asyncua/tools.py", line 595, in uadiscover
    run(_uadiscover())
  File "/home/njames/repos/opcua-asyncio/asyncua/tools.py", line 28, in run
    return asyncio.run(coro)
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/njames/repos/opcua-asyncio/asyncua/tools.py", line 634, in _uadiscover
    for (n, v) in endpoint_to_strings(ep):
  File "/home/njames/repos/opcua-asyncio/asyncua/tools.py", line 461, in endpoint_to_strings
    ('Server Certificate', cert_to_string(ep.ServerCertificate)),
  File "/home/njames/repos/opcua-asyncio/asyncua/tools.py", line 450, in cert_to_string
    from ..crypto import uacrypto
ValueError: attempted relative import beyond top-level package
```

This is fixed by changing 
`from ..crypto import uacrypto`
to
`from .crypto import uacrypto`

**Comment by driftregion** [comment]
fixed in https://github.com/FreeOpcUa/opcua-asyncio/commit/870dc85b8e506b1ca465435973e1283f0d120bcc
