### ISSUE TITLE
Memory leak in Master

### ISSUE THREAD

**Issue by mar-ar** [FreeOpcUa/opcua-asyncio#296]
Hey,

I found a memory leak in the current master branch. My server was running on the last release 0.8.4 and there was no Probem.
Then I updated the library to the current master and realized a memory leak. First I thought that I have a leak in my code but now I found the error in the library.

To detect the leak I logged like this: (simplified)
import objgraph
objgraph.show_growth(limit=20, file=myFile)

Then I found that every 10 seconds there is one more frame and coroutine
frame          991        +1
coroutine      989        +1

Afterwards I searched the guilty pull request with the result #272 
I just deleted line 139 and everything worked fine again.

Now we need to find out if the intended fix still works. 
I dont know why we need this recursion there. 

Can someone help me to fix that again?

best regards

**Comment by mar-ar** [comment]
I just thought about it and I think I found the fault:

We need to replace the last line.
`
await self._await_closing_tasks()
`
into
`
self.iserver.loop.create_task(self._await_closing_tasks())
`

**Comment by joncutting** [comment]
I think I just started seeing this today after switching from 0.8.4 to master.

When interrupting my program with Ctrl-C I get this:

2020-09-24 09:58:37,264 - asyncio - ERROR: unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<main() done, defined at C:/mystuff/myserver.py:575> exception=RecursionError('maximum recursion depth exceeded while calling a Python object')>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Python38\lib\asyncio\base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
  File "C:\Python38\lib\asyncio\windows_events.py", line 779, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/mystuff/myserver.py", line 595, in main
    await server.main()
  File "C:/mystuff/myserver.py", line 222, in main
    await self._server.stop()
  File "C:\mystuff\env\lib\site-packages\asyncua\server\server.py", line 382, in stop
    await self.bserver.stop()
  File "C:\mystuff\env\lib\site-packages\asyncua\server\binary_server_asyncio.py", line 149, in stop
    await self.cleanup_task
  File "C:\mystuff\env\lib\site-packages\asyncua\server\binary_server_asyncio.py", line 170, in _await_closing_tasks
    await self._await_closing_tasks()
  File "C:\mystuff\env\lib\site-packages\asyncua\server\binary_server_asyncio.py", line 170, in _await_closing_tasks
    await self._await_closing_tasks()
  File "C:\mystuff\env\lib\site-packages\asyncua\server\binary_server_asyncio.py", line 170, in _await_closing_tasks
    await self._await_closing_tasks()
  [Previous line repeated 981 more times]
  File "C:\mystuff\env\lib\site-packages\asyncua\server\binary_server_asyncio.py", line 169, in _await_closing_tasks
    await asyncio.sleep(10)
  File "C:\Python38\lib\asyncio\tasks.py", line 644, in sleep
    h = loop.call_later(delay,
  File "C:\Python38\lib\asyncio\base_events.py", line 687, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
  File "C:\Python38\lib\asyncio\base_events.py", line 702, in call_at
    timer = events.TimerHandle(when, callback, args, self, context)
  File "C:\Python38\lib\asyncio\events.py", line 106, in __init__
    super().__init__(callback, args, loop, context)
  File "C:\Python38\lib\asyncio\events.py", line 34, in __init__
    context = contextvars.copy_context()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by Randelung** [comment]
This line is problematic:
https://github.com/FreeOpcUa/opcua-asyncio/blob/cd8b41d828e154b46d8aecc69973805ce0382dc1/asyncua/server/binary_server_asyncio.py#L170
As oroulet mentioned in the original pull request #272, the method never returns, building an endless call chain. The whole method would have to be refactored to be iterative instead of recursive (or use tail recursion, but I'm wary of these kind of optimizations that you can't really control or verify).

```python
    async def _await_closing_tasks(self, recursive=True):
        while recursive:
            while self.closing_tasks:
                task = self.closing_tasks.pop()
                try:
                    await task
                except asyncio.CancelledError:
                    # this means a stop request has been sent, it should not be catched
                    raise
                except:
                    logger.exception("Unexpected crash in BinaryServer._await_closing_tasks")
            if recursive:
                await asyncio.sleep(10)
```

I haven't deep dived into what the cleanup does or if there's other potential issues, but I think the symptoms described by the crash and memory trace would match.
Thoughts?

**Comment by swamper123** [comment]
@Randelung @mar-ar Is that still an issue in master? Otherwise I would close that issue.

**Comment by mar-ar** [comment]
I think you can close it.

**Comment by Randelung** [comment]
No, don't close it, since nothing has actually changed...

**Comment by oroulet** [comment]
so close?

**Comment by Randelung** [comment]
Yes.
