### ISSUE TITLE
NodeId of type GUID that is parsed from string can't be converted to binary

### ISSUE THREAD

**Issue by cbergmiller** [FreeOpcUa/opcua-asyncio#49]
When try to use a Node that is instantiated wit a GUID type string:
```python
var = client.get_node("ns=4;g=35d5f86f-2777-4550-9d48-b098f5ee285c")
```
an exception is raised when it is converted to binary:
```
Traceback (most recent call last):
  File "client-minimal.py", line 30, in main
    print("My variable", var, await var.get_value())
  File "..\asyncua\common\node.py", line 164, in get_value
    result = await self.get_data_value()
  File "..\asyncua\common\node.py", line 173, in get_data_value
    return await self.get_attribute(ua.AttributeIds.Value)
  File "..\asyncua\common\node.py", line 284, in get_attribute
    result = await self.server.read(params)
  File "..\asyncua\client\ua_client.py", line 343, in read
    data = await self.protocol.send_request(request)
  File "..\asyncua\client\ua_client.py", line 134, in send_request
    self._send_request(request, timeout, message_type),
  File "..\asyncua\client\ua_client.py", line 114, in _send_request
    binreq = struct_to_binary(request)
  File "..\asyncua\ua\ua_binary.py", line 246, in struct_to_binary
    packet.append(to_binary(uatype, val))
  File "..\asyncua\ua\ua_binary.py", line 269, in to_binary
    return struct_to_binary(val)
  File "..\asyncua\ua\ua_binary.py", line 241, in struct_to_binary
    packet.append(list_to_binary(uatype[6:], val))
  File "..\asyncua\ua\ua_binary.py", line 281, in list_to_binary
    pack = [to_binary(uatype, el) for el in val]
  File "..\asyncua\ua\ua_binary.py", line 281, in <listcomp>
    pack = [to_binary(uatype, el) for el in val]
  File "..\asyncua\ua\ua_binary.py", line 269, in to_binary
    return struct_to_binary(val)
  File "..\asyncua\ua\ua_binary.py", line 246, in struct_to_binary
    packet.append(to_binary(uatype, val))
  File "..\asyncua\ua\ua_binary.py", line 259, in to_binary
    return pack_uatype(vtype, val)
  File "..\asyncua\ua\ua_binary.py", line 175, in pack_uatype
    return nodeid_to_binary(value)
  File "..\asyncua\ua\ua_binary.py", line 302, in nodeid_to_binary
    Primitives.Guid.pack(nodeid.Identifier)
  File "..\asyncua\ua\ua_binary.py", line 90, in pack
    f1 = Primitives.UInt32.pack(guid.time_low)
AttributeError: 'str' object has no attribute 'time_low'
```
In `Node._from_string()` the uid string is used as `identifier`. I guess it should be parsed as `UUID` instance instead. A test for guid NodeIds from strings should also be added.

**Comment by Bawwa-cmd** [comment]
@cbergmiller Were you able to read your node? Would you mind dropping here the code you used to get_node from GUID ?
