### ISSUE TITLE
Register to discovery not working

### ISSUE THREAD

**Issue by SeiteBroken** [FreeOpcUa/opcua-asyncio#564]
Im new to opcua-asyncio and i tried this code

```
import logging
import asyncio
import sys
sys.path.insert(0, "..")

from asyncua import ua, Server
from asyncua.common.methods import uamethod



@uamethod
def func(parent, value):
    return value * 2


async def main():
    _logger = logging.getLogger('asyncua')

    server = Server()
    await server.init()
    server.set_endpoint('opc.tcp://0.0.0.0:4841/freeopcua/server/')


    uri = 'http://examples.freeopcua.github.io'
    idx = await server.register_namespace(uri)
    

    await server.register_to_discovery("opc.tcp://localhost:4840", 60)

    myobj = await server.nodes.objects.add_object(idx, 'MyObject')
    myvar = await myobj.add_variable(idx, 'MyVariable', 6.7)

    await myvar.set_writable()
    await server.nodes.objects.add_method(ua.NodeId('ServerMethod', 2), ua.QualifiedName('ServerMethod', 2), func, [ua.VariantType.Int64], [ua.VariantType.Int64])
    _logger.info('Starting server!')
    async with server:
        while True:
            await asyncio.sleep(1)
            new_val = await myvar.get_value() + 0.1
            _logger.info('Set value of %s to %.1f', myvar, new_val)
            await myvar.write_value(new_val)


if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)

    asyncio.run(main(), debug=True)

````
I only got this from the LDS log:

````
Thu May 06 15:51:39 [5644]: ualds_endpoint_callback called: Event=SecureChannelOpened, SecureChanneldId=0x00000002, uStatus=0x00000000
Thu May 06 15:51:39 [5644]: ualds_endpoint_callback called: Event=SecureChannelOpenVerifyCertificate, SecureChanneldId=0x00000002, uStatus=0x800B0000
````

And this from the terminal:

````
DEBUG:asyncio:Using proactor: IocpProactor
INFO:root:No user manager specified. Using default permissive manager instead.
INFO:asyncua.server.internal_session:Created internal session Internal
INFO:asyncua.server.address_space:add_node: while adding node i=15957, requested parent node i=11715 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=15958, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=15959, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=15960, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=15961, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=15962, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=15963, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=15964, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=16134, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=16135, requested parent node i=15957 does not exists
INFO:asyncua.server.address_space:add_node: while adding node i=16136, requested parent node i=15957 does not exists
INFO:asyncua.client.client:connect
INFO:asyncua.client.ua_client.UaClient:opening connection
WARNING:asyncio:Executing <Task pending name='Task-1' coro=<main() running at c:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\server.py:28> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000023BF92BF2B0>()] created at C:\Users\benni\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py:424> cb=[_run_until_complete_cb() at C:\Users\benni\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py:184] created at C:\Users\benni\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py:621> took 1.610 seconds
DEBUG:asyncio:Get address info localhost:4840, type=<SocketKind.SOCK_STREAM: 1>
DEBUG:asyncio:Getting address info localhost:4840, type=<SocketKind.SOCK_STREAM: 1> took 16.000ms: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 4840, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 4840))]
DEBUG:asyncio:<asyncio.TransportSocket fd=492, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 57477, 0, 0), raddr=('::1', 4840, 0, 0)> connected to localhost:4840: (<_ProactorSocketTransport fd=492 read=<_OverlappedFuture pending overlapped=<pending, 0x23bfcfed820> cb=[_ProactorReadPipeTransport._loop_reading()] created at C:\Users\benni\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py:465>>, <asyncua.client.ua_client.UASocketProtocol object at 0x0000023BF92BFA30>)
INFO:asyncua.client.ua_client.UASocketProtocol:open_secure_channel
DEBUG:asyncua.client.ua_client.UASocketProtocol:Sending: OpenSecureChannelRequest(TypeId:i=446, RequestHeader:RequestHeader(AuthenticationToken:i=0, Timestamp:2021-05-06 13:51:39.839101, RequestHandle:1, ReturnDiagnostics:0, AuditEntryId:None, TimeoutHint:1000, AdditionalHeader:ExtensionObject(TypeId:i=0, Encoding:0, None bytes)), Parameters:OpenSecureChannelParameters(ClientProtocolVersion:0, RequestType:0, SecurityMode:1, ClientNonce:b'', RequestedLifetime:3600000))
INFO:asyncua.client.ua_client.UaClient:create_session
DEBUG:asyncua.client.ua_client.UASocketProtocol:Sending: CreateSessionRequest(TypeId:i=461, RequestHeader:RequestHeader(AuthenticationToken:i=0, Timestamp:2021-05-06 13:51:39.848075, RequestHandle:2, ReturnDiagnostics:0, AuditEntryId:None, TimeoutHint:4000, AdditionalHeader:ExtensionObject(TypeId:i=0, Encoding:0, None bytes)), Parameters:CreateSessionParameters(ClientDescription:ApplicationDescription(ApplicationUri:urn:freeopcua:client, ProductUri:urn:freeopcua.github.io:client, ApplicationName:LocalizedText(Encoding:2, Locale:None, Text:Pure Python Async. Client), ApplicationType:1, GatewayServerUri:None, DiscoveryProfileUri:None, DiscoveryUrls:[]), ServerUri:None, EndpointUrl:opc.tcp://localhost:4840, SessionName:Pure Python Async. Client Session1, ClientNonce:b'N+\x9bc\x8a2\x19\x98w,+k\xd6\xfc\x953\x15\xd8S.\x9f\x9f\xff\xebE\xc1\x97cK\xc2\xfc\x9f', ClientCertificate:None, RequestedSessionTimeout:3600000, MaxResponseMessageSize:0))
WARNING:asyncua.uaprotocol:Received an error: MessageAbort(error:StatusCode(BadServiceUnsupported), reason:None)
CRITICAL:asyncua.client.ua_client.UASocketProtocol:Received an error: MessageAbort(error:StatusCode(BadServiceUnsupported), reason:None)
ERROR:asyncua.client.ua_client.UASocketProtocol:Exception raised while parsing message from server
Traceback (most recent call last):
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\ua_client.py", line 169, in _call_callback
    self._callbackmap[request_id].set_result(body)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\ua_client.py", line 81, in _process_received_data
    self._process_received_message(msg)
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\ua_client.py", line 105, in _process_received_message
    self._call_callback(0, ua.UaStatusCodeError(msg.Error.value))
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\ua_client.py", line 171, in _call_callback
    raise ua.UaError(f"No request found for request id: {request_id}, pending are {self._callbackmap.keys()}")
asyncua.ua.uaerrors._base.UaError: No request found for request id: 0, pending are dict_keys([2])
INFO:asyncua.client.ua_client.UASocketProtocol:Request to close socket received
INFO:asyncua.client.ua_client.UASocketProtocol:Socket has closed connection
WARNING:asyncua.client.ua_client.UaClient:disconnect_socket was called but connection is closed
DEBUG:asyncio:Close <ProactorEventLoop running=False closed=False debug=True>
Traceback (most recent call last):
  File "c:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\server.py", line 49, in <module>
    asyncio.run(main(), debug=True)
  File "C:\Users\benni\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\benni\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\server.py", line 28, in main
    await server.register_to_discovery("opc.tcp://localhost:4840", 60)
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\server\server.py", line 239, in register_to_discovery
    await self._discovery_clients[url].connect()
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\client.py", line 244, in connect
    await self.create_session()
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\client.py", line 366, in create_session
    response = await self.uaclient.create_session(params)
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\ua_client.py", line 299, in create_session
    data = await self.protocol.send_request(request)
  File "C:\Users\benni\OneDrive\Dokumente\Neuer Ordner\Python\.venv\lib\site-packages\asyncua\client\ua_client.py", line 150, in send_request
    raise ConnectionError("Connection is closed") from None
ConnectionError: Connection is closed
````

Can somebody tell me where my mistake is ?

**Comment by AndreasHeine** [comment]
your discoveryserver is not a discoveryserver -> MessageAbort(error:StatusCode(BadServiceUnsupported)

**Comment by AndreasHeine** [comment]
how is the discoveryserver configured?

**Comment by SeiteBroken** [comment]
I used this LDS Release:
https://opcfoundation.org/developer-tools/samples-and-tools-unified-architecture/local-discovery-server-lds/

**Comment by AndreasHeine** [comment]
ok! 
looks like we have a bug -> https://reference.opcfoundation.org/v104/GDS/docs/4.2.2/

we only call register and not register2 up front...

https://github.com/FreeOpcUa/opcua-asyncio/blob/af5a31c0db2b4f2469cdc7c169a0aa812b606152/asyncua/server/server.py#L227

**Comment by SeiteBroken** [comment]
Okay, so there is a bug in asycua.
Thank you!

**Comment by AndreasHeine** [comment]
i can reproduce the error but the weird part is i cant connect to the lds at all it always throws BadServiceUnsupported...

**Comment by AndreasHeine** [comment]
https://reference.opcfoundation.org/v104/Core/docs/Part7/5.2/
ServerDiscovery   
RegisterCall
 the RegisterServer Service to register itself (OPC UA Server) with an external Discovery Service via a secure channel with a SecurityMode other than NONE.

i am not sure that we need a session for that!?

https://github.com/FreeOpcUa/opcua-asyncio/blob/af5a31c0db2b4f2469cdc7c169a0aa812b606152/asyncua/server/server.py#L227

https://github.com/FreeOpcUa/opcua-asyncio/blob/af5a31c0db2b4f2469cdc7c169a0aa812b606152/asyncua/client/client.py#L233

**Comment by AndreasHeine** [comment]
@SeiteBroken https://github.com/FreeOpcUa/opcua-asyncio/pull/1193
