### ISSUE TITLE
Server sends DataChangeFilter instead of MonitoringFilter

### ISSUE THREAD

**Issue by Randelung** [FreeOpcUa/opcua-asyncio#688]
**Describe the bug** <br />
I received this bug report for our software using asyncua:
> We have encountered a problem connecting to the Ticos OPC UA Server, when using a ‘DataChangeFilter’ in order to be notified when the Timestamp of a node changes, even its Value is not changed.
The Exception that prevents us from connecting to the server is this:
> 
> 14:16:09,864 ERROR [com.prosysopc.ua.client.UaClient] (PublishTask-com.prosysopc.ua.client.UaClient@2179b53a) Exception in ServerStatusListener: java.lang.ClassCastException: org.opcfoundation.ua.core.DataChangeFilter cannot be cast to org.opcfoundation.ua.core.MonitoringFilterResult
> 
> Analyzing to problem, after some clue we got in this error reported in the Prosys ‘forum’:
https://forum.prosysopc.com/forum/opc-ua-java-sdk/java-sdk-cast-error/
We can confirm (by debugging the answer from Ticos) that this is the very same problem.

**To Reproduce**<br />
Trying to obtain.
There is code in the linked bug report.

**Expected behavior**<br />
Again the quote from the mail:
> If you open this document attached [[OPC Foundation documentation part 4 - Services](https://reference.opcfoundation.org/v104/Core/docs/Part4/5.12.2/)], and go to the paragraph 5.12.2 ‘CreateMonitoredItems’, you can see that the Response parameter (5.12.2.2), for the ‘filterResult’ is either null (all the other suppliers return null), or a MonitoringFilter. However, Ticos is answering this ‘filterResult’ with a ‘DataChangeFilter’. This produces an internal error in the Prosys SDK library and the connection is not possible.
>
> From the documentation, this Response:
>
>> “Contains any revised parameter values or error results associated with the MonitoringFilter specified in requestedParameters. This parameter may be null if no errors occurred. The MonitoringFilterResult parameter type is an extensible parameter type specified in 7.17. ”
>
>Leaving aside that Ticos is answering with the wrong object. What may be happening here is that they don’t support the ‘Filtering’ for Timestamp, which could indicate that they notify changes for Timestamps without having to specify the filter.

I tried to confirm the last statement, but it appears to not be true. I connected with an uaExpert and rewrote the same node with a new timestamp and uaExpert was not updated. It might be a filter in my code, though, still making 100% sure.

**Screenshots**<br />
\-

**Version**<br />
Python-Version: 3.9.5<br />
opcua-asyncio Version (e.g. master branch, 0.9): 0.9.14 (commit 854c2e4962eee9aa45bcd5f29df32afe6618baa9)

Cheers

**Comment by Randelung** [comment]
Okay, I found a way to confirm the timestamp statement.
- Monitor an item on uaExpert
- Changing the MonitoredItem settings and explicitly activate the DataChangeFilter including Timestamp
- Rewrite the node
- Don't receive an update
- Delete the monitored item and recreate it
- See new updated timestamp

**Comment by mstoffel-sag** [comment]
Have the same issue.  We are using prosys opc-ua java sdk. When I try to do a subscription I get:

Subscription, subscriptionParameters=SubscriptionParameters(samplingRate=3000, deadbandType=None, deadbandValue=null, ranges=, queueSize=10, dataChangeTrigger=StatusValue, discardOldest=true), cyclicReadParameters=CyclicReadParameters(rate=50, maxAge=0.0)))}) for server: 9059374264
2024-03-21 08:41:59.456 ERROR 1 --- [    scheduler-9] c.c.o.c.g.s.SubscriptionUpdateScheduler  : Execution of updateTask failed by callable returns java.lang.ClassCastException: class com.prosysopc.ua.stack.core.DataChangeFilter cannot be cast to class com.prosysopc.ua.stack.core.MonitoringFilterResult (com.prosysopc.ua.stack.core.DataChangeFilter and com.prosysopc.ua.stack.core.MonitoringFilterResult are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @c038203) with error
 
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class com.prosysopc.ua.stack.core.DataChangeFilter cannot be cast to class com.prosysopc.ua.stack.core.MonitoringFilterResult (com.prosysopc.ua.stack.core.DataChangeFilter and com.prosysopc.ua.stack.core.MonitoringFilterResult are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @c038203)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.cumulocity.opcua.client.gateway.subscription.SubscriptionUpdateScheduler.doUpdate(SubscriptionUpdateScheduler.java:145)
	at com.cumulocity.opcua.client.gateway.subscription.SubscriptionUpdateScheduler.update(SubscriptionUpdateScheduler.java:75)
	at jdk.internal.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class com.prosysopc.ua.stack.core.DataChangeFilter cannot be cast to class com.prosysopc.ua.stack.core.MonitoringFilterResult (com.prosysopc.ua.stack.core.DataChangeFilter and com.prosysopc.ua.stack.core.MonitoringFilterResult are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @c038203)
	at com.prosysopc.ua.client.Subscription.a(SourceFile:1114)
	at com.prosysopc.ua.client.Subscription.a(SourceFile:1173)
	at com.prosysopc.ua.client.Subscription.createMonitoredItems(SourceFile:1678)
	at com.prosysopc.ua.client.Subscription.createItems(SourceFile:1643)
	at com.prosysopc.ua.client.UaClient.a(SourceFile:5522)
	at com.prosysopc.ua.client.UaClient.addSubscription(SourceFile:848)
	at com.cumulocity.opcua.client.OpcuaSubscriber.subscribe(OpcuaSubscriber.java:106)
	at com.cumulocity.opcua.client.OpcuaClientImpl.subscribe(OpcuaClientImpl.java:392)
	at com.cumulocity.opcua.client.gateway.subscription.UaSubscriptionService.createServerSubscription(UaSubscriptionService.java:240)
	at com.cumulocity.opcua.client.gateway.subscription.UaSubscriptionService.applySubscriptions(UaSubscriptionService.java:165)
	at com.cumulocity.opcua.client.gateway.subscription.UaSubscriptionService.applySubscriptions(UaSubscriptionService.java:90)
	at com.cumulocity.opcua.client.gateway.subscription.CompositeSubscriptionService.applyForType(CompositeSubscriptionService.java:100)
	at com.cumulocity.opcua.client.gateway.subscription.CompositeSubscriptionService.applySubscriptions(CompositeSubscriptionService.java:53)
	at com.cumulocity.opcua.client.gateway.subscription.UpdateServerSubscriptionTask.subscribeWithDeviceTypeAndNode(UpdateServerSubscriptionTask.java:231)
	at com.cumulocity.opcua.client.gateway.subscription.UpdateServerSubscriptionTask.updateSubscriptionForMappedNode(UpdateServerSubscriptionTask.java:191)
	at com.cumulocity.opcua.client.gateway.subscription.UpdateServerSubscriptionTask.updateSubscriptionForServer(UpdateServerSubscriptionTask.java:154)
	at com.cumulocity.opcua.client.gateway.subscription.UpdateServerSubscriptionTask.run(UpdateServerSubscriptionTask.java:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 common frames omitted
Is there any fix in the making?

**Comment by mstoffel-sag** [comment]
Hi, Any way to work around that?
