### ISSUE TITLE
Exception raised when running for long time

### ISSUE THREAD

**Issue by leomoshe** [FreeOpcUa/opcua-asyncio#881]
I wrote the following code

    async def main(config):
      try:
          url = config["url"]
          async with Client(url=url) as client:
              await client.connect()
              handler = SubHandler()
              subscription = await client.create_subscription(500, handler) # 10
              subscribed_nodes = config["subscribed_nodes"]
              server_status_current_time = client.get_node(ua.ObjectIds.Server_ServerStatus_CurrentTime)
              nodes = [server_status_current_time]
              for subscribed_node in subscribed_nodes:
                  node = client.get_node(subscribed_node)
                  nodes.append(node)
              handle = await subscription.subscribe_data_change(nodes)
              global _handler, _handle, _client, _subscription
              _handle = handle
              _client = client
              _subscription = subscription
              await asyncio.sleep(0.1)
              while True:
                  await asyncio.sleep(1)
              client.disconnect()
      finally:
          print("Exit Python application")
          if _handle and _subscription:
              await _subscription.unsubscribe(_handle)
              await _subscription.delete()
          if _client:
              await _client.disconnect()

   
    if __name__ == "__main__":
        config_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "./configuration.json"))
        with open(config_path, 'r') as f:
            config = json.load(f)
        asyncio.run(main(config))

### requirements.txt
asyncua==0.9.92

The code continue to run in:
 
    while True:
        await asyncio.sleep(1)

### And obtain the following error when running for 6 - 10 hours:

**Exception raised while parsing message from server**
Traceback (most recent call last):
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\client\ua_client.py", line 78, in _process_received_d
    msg = self._connection.receive_from_header_and_body(header, buf)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\common\connection.py", line 344, in receive_from_head
    self._check_sym_header(security_header)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\common\connection.py", line 296, in _check_sym_header
    raise ua.UaError(f"Security token id {security_hdr.TokenId} has timed out " f"({timeout} < {datetime.utcnow()})")
asyncua.ua.uaerrors._base.UaError: **Security token id 12 has timed out (2022-05-12 21:20:38.893618 < 2022-05-15 06:28:32.133270)
Error while renewing session**
Traceback (most recent call last):
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\client\client.py", line 405, in _renew_channel_loop
    val = await self.nodes.server_state.read_value()
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\common\node.py", line 177, in read_value
    result = await self.read_data_value()
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\common\node.py", line 188, in read_data_value
    return await self.read_attribute(ua.AttributeIds.Value)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\common\node.py", line 302, in read_attribute
    result = await self.server.read(params)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\client\ua_client.py", line 362, in read
    data = await self.protocol.send_request(request)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\client\ua_client.py", line 148, in send_request
    raise ConnectionError("Connection is closed") from None
**ConnectionError: Connection is closed
Task exception was never retrieved**
future: <Task finished name='Task-3' coro=<Client._renew_channel_loop() done, defined at c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.ven 188, in read_data_value
 188, in read_data_value
    return await self.read_attribute(ua.AttributeIds.Value)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\common\node.py", line 302, in read_attribute
    result = await self.server.read(params)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\client\ua_client.py", line 362, in read
    data = await self.protocol.send_request(request)
  File "c:\Development\opc\Tools\opcua-asyncio-master\opcua-asyncio-master\.venv\lib\site-packages\asyncua\client\ua_client.py", line 148, in send_request      
    raise ConnectionError("Connection is closed") from None
**ConnectionError: Connection is closed**

As i understood one of the solutions is to retry connection.
How can I catch the exception?, How and where reconnect?

Regards

**Comment by swamper123** [comment]
You are right with the reconnect part. At the moment our Server kicks out Clients after a while, but the reconnection feature is not built in at the moment.

So what you need to do is:

1) create normal connection to the server
2) Subscribe everything you need
(Now it runs normally ... if you want you can check the servicelevel of the server and handle with that information as well)
3) In case of exceptions: unsubscribe, delete subscriptions, disconnect

and if 3) is done, you may wait a short time and start again with step 1). So a loop is what you want to do.
[One way can be the way AndreasHeine did](https://github.com/AndreasHeine/opcua-sub-to-websocket/blob/9f664cd2d6d7f3225ca7334f049c2ff5069ad755/client.py#L62)
